#!/usr/bin/python2.7
# -*- coding: utf-8 -*-
#
#   noun.py
#

from datetime import datetime

class Noun(object):
    """A German noun"""

    def __init__(self, noun):
        self.noun = noun
        self.created = datetime.now()
        self.updated = self.created #TODO Does this assign value?
        self.gender = ''

    def setGender(self, gender):
        self.gender = gender

class WikiNoun(Noun):
    """A German noun generated by the German Wiktionary"""

    def __init__(self, noun, ref, cat):
        Noun.__init__(self, noun, ref)
        self.category = cat

